
## => Site Settings
##############################
text_skin: default
highlight_theme: tomorrow-night
url     : https://the-random-dev.github.io/
baseurl : /
title   : The Random Dev | Developer
description: > 
  Full stack developer.
  Experience with embedded systems and backend developing.
  Learning devops culture.


## => Language and Timezone
##############################
lang: en
timezone: BR

## => Author and Social
##############################
author:
  type      : "person"
  name      : The Random Dev
  url       : "https://the-random-dev.hithub.com"
  avatar    : # path or url of avatar image (square)
  bio       : Full stack developer. Experience with embedded systems and backend developing.
  twitter   : the_random_dev
  github    : # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  instagram : the.random.dev

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: user_name/repo_name
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: "addthis"

  ## AddThis
  addthis:
    id: ra-5ea4c70a625bff14


## => Comments
##############################
comments:
  provider: "disqus"

  ## Disqus
  disqus:
    shortname: "the-random-dev-github-io"

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: "google" # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: 016468740577485883013:ojtodusjjrz

## => Analytics
##############################
analytics:
  provider: 'google' # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : UA-164591020-1 # Google Analytics id for the site
    anonymize_ip: true # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: false
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
